### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by james2doyle** [james2doyle/phileAdmin#1]
Feedback and questions about this plugin.

**Comment by bzerangue** [comment]
How do I access the admin portion? Are there any special settings that I need to call for this to work?

**Comment by james2doyle** [comment]
just enable the plugin like normal, then go to admin/login and it will redirect you

**Comment by bzerangue** [comment]
this looks really cool! and would be quite useful!!!!!

**Comment by jacmgr** [comment]
I'll try it tonight (9 hours from now). phile needs something like this, but agree it should be limited.

**Comment by jacmgr** [comment]
Tried it. Liked it. You can see it here on my site for temporary.

I did fresh install of phile and added the phileadmin plugin. 
http://www.jhinline.com/philecms/phileadmintest/

Anyway I couldn't get a login screen to show.  But still see the features. It is on track, just get those planned features to work as minimally as possible.

**Comment by james2doyle** [comment]
There is a login screen, but login is disabled for testing. 

Here is the admin panel 

http://www.jhinline.com/philecms/phileadmintest/admin/pages

**Comment by jacmgr** [comment]
right, it auto redirects there.  The link I gave was a page where you can click to the admin panel or click to some notes I made about the plugin.

**Comment by pschmitt** [comment]
Nice, really nice. Won't be using it that much since i don't trust any GUI. But still that's a very good plugin.

**Comment by james2doyle** [comment]
The idea is ease some pains of FTP for clients. So far I have had mixed
results with people. Some people get it right away. Some people keep
breaking everything!

On Thu, Mar 13, 2014 at 9:28 AM, Philipp Schmitt
notifications@github.comwrote:

> Nice, really nice. Won't be using it that much since i don't trust any
> GUI. But still that's a very good plugin.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/james2doyle/phileAdmin/issues/1#issuecomment-37532335
> .

## 

_James Doyle_

_t:  @james2doyle https://twitter.com/james2doylew: ohdoylerules.com
http://ohdoylerules.com_

**Comment by kursusHC** [comment]
Very nice draft, thanks for this. It will let me drop elFinder for my Phile projects. 
I think a nice addition would be a folder manager for the Media page.

**Comment by james2doyle** [comment]
For a heads up everyone, right now all the media gets dumped in the folder
that is defined in the phileAdmin config.

Folder management would be cool, complicated, but cool.

On Thu, Mar 13, 2014 at 1:54 PM, kursusHC notifications@github.com wrote:

> Very nice draft, thanks for this. It will let me drop elFinder for my
> Phile projects.
> I think a nice addition would be a folder manager for the Media page.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/james2doyle/phileAdmin/issues/1#issuecomment-37564976
> .

## 

_James Doyle_

_t:  @james2doyle https://twitter.com/james2doylew: ohdoylerules.com
http://ohdoylerules.com_

**Comment by Frodox** [comment]
First of all, thank you for the invitation and sorry for a long reply, I way busy during the week :)

You have done great work! The result is the light-weight, powerful and easy to use content management admin panel =) Looks pretty cool! The on-line-markdown-rendering is the killer feature! Thank you :+1: 

If you want a bit of constructive criticism... I would try to say only about main workflow things (i mean, you already know about all bugs :D )
- as to secure, did you plan to make some option to change the default admin area? i.e. from `admin/login` somewhere else(configurable in settings)? I know guys that like to brute-force sites with common admin-urls =) (yup, I plan to use new admin-url together with htpasswd)
- Pages: if you select some page and then go to Editing, [save] and return back, then there will be selected the top(first) one again, but not the previously edited (expected behaviour)
- Pages: in case of a lot of articles, say 30 (ie more then one "screen"), if you scroll window down and select some page in the bottom, you will not see a page details (it will be at the top of page). Is it bug/feature? :) Also, in case of 100+ pages, there will be very long "Pages" page. Did you think about some hierarchy (for example, you can use content-folder's one, or smth else) ?
- Media: how should it work? :) I create `content/uploads` folder with 777 (test) perms. If I select a file, there appears an icon with green tick and a warning (below drag'n'drop area), : 
  `Warning: opendir(/var/www/bt/www/blog/content/uploads/): failed to open dir: No such file or directory in /var/www/bt/www/blog/plugins/phileAdmin/plugin.php on line 165`
  Actually,  there's appeared file in the _content/uploads_ folder with temp-name, but: if a reopen _Media_ page, no one media is listed (I expect a list of already uploaded media). Ignore it, if it just a bug :)

**Comment by james2doyle** [comment]
Thanks. I can address everything 1 by 1.
- I haven't put the URL access in the config. Because each URL is mapped to a specific function. But you could change [this line or I can add this option to the config](https://github.com/james2doyle/phileAdmin/blob/master/plugin.php#L58) and it would allow custom URLs. But the `login` part, would still be the same.
- Thats a good idea. I can set it with localstorage or something.
- Hmmm. maybe pagination or a nicer scrolling list is the solution here. My site has about 80 articles so I can see where this could be a pain.
- I haven't had any problems with the media uploading. I used the `CONTENT_DIR` constant for finding the content folder. You can change the [uploads dir in the config](https://github.com/james2doyle/phileAdmin/blob/master/config.php#L8). Try changing it to something else and seeing if that works.

**Comment by Frodox** [comment]
> I can add this option to the config and it would allow custom URLs. 

It would be great :)

> But the login part, would still be the same.

Yes, I mean only `admin` part.

Well, what I found about Media:

not matter what folder to choice, I get in log next lines, when open **Pages** only:

```
[Sun Mar 16 00:06:15 2014] [error] [client 127.0.0.1] PHP Notice:  Undefined index: meta in /var/www/bt/www/blog/plugins/phileAdmin/views/pages.php on line 17, referer: http://bt.com/blog/admin/media
[Sun Mar 16 00:06:15 2014] [error] [client 127.0.0.1] PHP Notice:  Undefined index: meta in /var/www/bt/www/blog/plugins/phileAdmin/views/pages.php on line 22, referer: http://bt.com/blog/admin/media
[Sun Mar 16 00:06:15 2014] [error] [client 127.0.0.1] PHP Warning:  Invalid argument supplied for foreach() in /var/www/bt/www/blog/plugins/phileAdmin/views/pages.php on line 22, referer: http://bt.com/blog/admin/media
```

I don't know if it take any matter.
Uploading works fine - files appear in correct folder, but.. you didn't reply - what is the idea?
How to use uploaded file? :) 
I chose a file, say, `my-dog.jpg`, after uploading it will be smth like `my-dog-1394913665.jpg`, but ... I don't know it! Should I connect via ssh to know, which name I should use in my article for this image? :D I think, the list of uploaded media is a feature that should be added _in order for this to work_ :)

**Comment by james2doyle** [comment]
Media is still a little wonky. The thumbnails only work for images right
now.

Also when you upload a file, you can see the name of it at the bottom of
the thumbnail. Also you can left click the thumbnail and it will take you
to the image in a new tab, where you can copy the URL.

I would do a right-click-copy-link-address in order to get the link.

On Sat, Mar 15, 2014 at 4:33 PM, Christian notifications@github.com wrote:

> I can add this option to the config and it would allow custom URLs.
> 
> It would be great :)
> 
> But the login part, would still be the same.
> 
> Yes, I mean only admin part.
> 
> Well, what I found about Media:
> 
> not matter what folder to choice, I get in log next lines, when open
> _Pages_ only:
> 
> [Sun Mar 16 00:06:15 2014] [error] [client 127.0.0.1] PHP Notice:  Undefined index: meta in /var/www/bt/www/blog/plugins/phileAdmin/views/pages.php on line 17, referer: http://bt.com/blog/admin/media
> [Sun Mar 16 00:06:15 2014] [error] [client 127.0.0.1] PHP Notice:  Undefined index: meta in /var/www/bt/www/blog/plugins/phileAdmin/views/pages.php on line 22, referer: http://bt.com/blog/admin/media
> [Sun Mar 16 00:06:15 2014] [error] [client 127.0.0.1] PHP Warning:  Invalid argument supplied for foreach() in /var/www/bt/www/blog/plugins/phileAdmin/views/pages.php on line 22, referer: http://bt.com/blog/admin/media
> 
> I don't know if it take any matter.
> Uploading works fine - files appear in correct folder, but.. you didn't
> reply - what is the idea?
> How to use uploaded file? :)
> I chose a file, say, my-dog.jpg, after uploading it will be smth like
> my-dog-1394913665.jpg, but ... I don't know it! Should I connect via ssh
> to know, which name I should use in my article for this image? :D I think,
> the list of uploaded media is a feature that should be added _in order
> for this to work_ :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/james2doyle/phileAdmin/issues/1#issuecomment-37737163
> .

## 

_James Doyle_

_t:  @james2doyle https://twitter.com/james2doylew: ohdoylerules.com
http://ohdoylerules.com_

**Comment by Frodox** [comment]
> Media is still a little wonky. The thumbnails only work for images right
> now.

oh, fine. I just didn't check on real image actually (only on text-files) :D
But any way, the list of uploaded media - good feature, imho

**Comment by ksbckr** [comment]
Looks very promising. Just tried it on my local system for now. Gonna take a closer look the next days.
