### ISSUE TITLE
Saving pages in new subdirectories

### ISSUE THREAD

**Issue by trst** [james2doyle/phileAdmin#11]
I love the idea of the admin area for sheer convenience—especially when I'm away from my regular computer, however, I noticed that I am unable to create a new page in a subdirectory that doesn't (yet) exist. Is this a permissions issue? Or something functionality that hasn't been added?

**Comment by james2doyle** [comment]
I'll have to add this feature in the future

**Comment by james2doyle** [comment]
Closed via #12
