### ISSUE TITLE
After updating to latest, I can't get it to work

### ISSUE THREAD

**Issue by lydenyardley** [james2doyle/phileAdmin#13]
[8] Trying to get property of non-object in /Applications/XAMPP/xamppfiles/htdocs/yap/plugins/phile/adminPanel/Classes/Plugin.php on line 58 [8](Exception-Wiki)
Exception thrown in file /Applications/XAMPP/xamppfiles/htdocs/yap/plugins/phile/errorHandler/Classes/Development.php on line 32.

This is the error_log:

2014-07-04 11:48:23 No user file found for fb7b80115607d0685223137eed7b19b3575a2e9c

**Comment by james2doyle** [comment]
Go to your users folder and delete everything inside it and then go to /admin

**Comment by lydenyardley** [comment]
There was just an empty index.html.
Deleted it, but still getting the same :-(

**Comment by james2doyle** [comment]
Well the first time you run the admin it creates a new user. Have you filled out your [encryption key](https://github.com/PhileCMS/Phile/blob/master/config.php#L8)?

**Comment by lydenyardley** [comment]
Yeah that's filled in! But nothing is created in the users folder when running admin still.

**Comment by james2doyle** [comment]
I see what you mean. Im getting the error too. Let me try to fix it.

**Comment by james2doyle** [comment]
Closed this with aea4005b65f971b045a53b7869e30025fa38da56

**Comment by lydenyardley** [comment]
Great, no error now, but the site can't be viewed at all without logging in to Admin!

**Comment by james2doyle** [comment]
Fixed this with dc511e92fe7044780a6e18e39600b9e519edae9c
